import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { Inter } from "next/font/google";
import logo from "/public/logos/b.png";
import "../globals.css";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  weight: ["200", "400", "500", "600", "700"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${inter.className}   antialiased max-h-screen overflow-hidden`}
      >
        <nav className="flex  items-center pl-14  py-4 text-xl  border-b-2 border-stone-700 shadow-2xl  bg-background ">
          <Link href="/" className="flex-shrink-0">
            <Image src={logo} width={90} alt="Heavy dumbbel" />{" "}
          </Link>
        </nav>
        <main className="mt-5">{children}</main>
      </body>
    </html>
  );
}
